############### Parameters associated with the data ###############
input:

  # path to a text file where each line is either 
  #   1. forward_fastq,reverse_fastq
  #   OR
  #   2. sample.bam,sample.bai
  # cannot mix .fastqs with .bams
  manifest: 'samples'

  # reference genome database
  # reference: '/home/zamc8857/animal_svs/data/house-sparrow.fa'
  reference: 'house-sparrow.fa'

  # used to name output files. Not needed. If left blank,
  # defaults to the filename of the forward sequence
  sample_name: 'cloud-test-deployment'

############### Parameters associated with the run ###############
run:

  # temporary file store. Files will be deleted
  temp_dir: '../temp'

  # output any issues/progress to this location
  logs_dir: '../logs'

  # directory to save final output files
  output_dir: 'output'

############### Parameters associated with deployment ###############
deployment:

  # supported types: 'cloud', 'local'
  type: 'cloud'

    # if files are in the cloud, parameter should be 'remote', otherwise make it 'local'
    file_location: 'remote'

  # number of cores to use. If left at 0, max cores are used
  cores: 0

  # Service is ONLY used if deployment is set to 'cloud'
  # current supported services are: 'gcp', 
  service: 'gcp'

  # the project name. Right now, only supported for GCP project
  project_name: 'dcsc-fall-2020'

  # instance machine type
  # documentation for Google Cloud Compute Enginer machine types can be seen here
  # https://cloud.google.com/compute/docs/machine-types
  # NOTE: for extra large files, its advised to get at least 16 GB ram if not more
  # and at least the size of all files for the hard drive.
  gcp_instance:
      machine_type: 'e2-standard-4'
      disk_space: '40' # in GB
      ram_size: '16' # in GB

      # documentation for region and zone found here
      # https://cloud.google.com/compute/docs/regions-zones
      region: 'us-central1'
      zone: 'us-central1-a'
